/**
 * Object which contains different constants used in the game. 
 * @type {Object}
 * @author Roman Pusec
 */
var Constants = {
	FPS: 60,
	MOUSE_OVER_FREQ: 5,
	COLOR_ONE: '#fff', 
	COLOR_TWO: '#000',
	TEXT_PADDING: 25,
	WM_SP_TO_BOTTOM: 40,
	GAME_ROOMS_PER_ROW: 3,
	GAME_ROOM_WAIT_TIME: 100,
	POLIGON_POINT_TYPE: [4, 6, 8, 10],
	PAWN_AMOUNT: 12,
	DISAPPEARANCE_DIST: 60,
	USER_PROFILE_MOVE: 50,
	GAME_ROOM_PADDING: 70,
	USER_PROFILE_AVATAR_SIZE: 30,
	FIRST_PLAYER: 1,
	SECOND_PLAYER: 2,
	CHECK_ROOM_AVAILABILITY_INTERVAL_DURATION: 2000,
	CHECK_OPPONENT_INTERVAL_DURATION: 3000,
	CHECK_IF_OPPONENT_IS_DONE_INTERVAL_DURATION: 3000,
	MAX_USERS_PER_ROOM: 2
};